#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SerialBlue.Resource", IsApplication=true)]

namespace SerialBlue
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int button_send = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int discoveralbe = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int edit_text_out = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int inLv = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int menu_bluetooth_key = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int menu_clear = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int menu_connect = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int menu_search = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int paired_devices = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int scan = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int title_left_text = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int title_paired_devices = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int title_right_text = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int toolbar = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int custom_title = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int device_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int DiagView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int message = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int toolbar = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int diag_top_menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int main_top_menu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int option_menu = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_bluetooth = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_bluetooth_on = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_action_connected = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_action_connecting = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_action_trash = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_action_unconnect = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ic_menu_search_holo_dark = 2130903046;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int Connect = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int Discoverable = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int bluetooth_not_available = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int bluetooth_not_opened = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int connect_device_failed = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int connect_device_lost = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int connect_device_ok = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int connecting_device = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int send = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int title_paired_devices = 2131034122;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int DialogTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int TitleTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
